version: '3.1'

services:

  wordpress:
        image: wordpress
        restart: always
        ports:
                - 8888:80
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: exampleuser
          WORDPRESS_DB_PASSWORD: examplepass
          WORDPRESS_DB_NAME: exampledb
        volumes:
        - /blog/html:/var/www/html

  db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: exampledb
          MYSQL_USER: exampleuser
          MYSQL_PASSWORD: examplepass
          MYSQL_ROOT_PASSWORD: '1'
        volumes:
         - /blog/db/:/var/lib/mysql
  phpadmin:
        image: phpmyadmin:5.1.1-fpm-alpine
        ports:
                - 7777:8080
        environment:
          MYSQL_ROOT_PASSWORD: '1'
            

